### ISSUE TITLE
a new error

### ISSUE THREAD

**Issue by oknixus** [AtomLinter/linter-phpcs#152]
Thanks very much. The problem of timeout was fixed, but bring a new error.
I'm sorry for this, but I have to tell you.

Thanks!

非常感谢您的努力，timeout的问题已经得到解决了，但是产生了一个新的问题，错误提示在下面、

真心感谢您为广大开发者带来了如此便捷高效的工具插件，非常感谢！

```
Error: PHP Notice: Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 115
PHP Notice: Undefined index: scope_closer in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 116
PHP Notice: Undefined index: in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 117
PHP Notice: Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 196
PHP Notice: Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 205

Error: PHP Notice:  Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 115
PHP Notice:  Undefined index: scope_closer in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 116
PHP Notice:  Undefined index:  in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 117
PHP Notice:  Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 196
PHP Notice:  Undefined index: scope_opener in /Users/KJRS/pear/share/pear/PHP/CodeSniffer/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php on line 205
    at ChildProcess.<anonymous> (/Users/KJRS/.atom/packages/linter-phpcs/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Arcanemagus** [comment]
Those are internal errors in `phpcs`, it looks like they are all in the `SwitchDeclarationSniff.php` file. You would need to file that there as it has nothing to do with this package :confused:.

**Comment by jyggen** [comment]
Something I've noticed is that PHPCS doesn't always handle PHP files with syntax errors that great. So either that or you have some edge case code that `SwitchDeclarationSniff` isn't too fond of yet :)
