### ISSUE TITLE
Error: PHP Notice: Undefined offset: 74 in /usr/local/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php on line 107

### ISSUE THREAD

**Issue by PC888** [AtomLinter/linter-phpcs#175]
Hey guys, I've just started receiving this error when editing php files. Not sure if I should be posting this here or at - https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

```text
Error: PHP Notice: Undefined offset: 74 in /usr/local/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php on line 107
    at ChildProcess.<anonymous> (/Users/paulcarter/.atom/packages/linter-phpcs/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I'm running linter-phpcs/linter with phpcs and the wpcs coding standards. It's been running fine since the install 1 week ago.

When I disable linter-phpcs the errors stop.

**Comment by jyggen** [comment]
Sounds like a PHPCS error to me. Some sniffs (especially custom/3rd-party sniffs) tend to error out when you have a syntax error in your code, or sometimes for other unknown reasons.

I'd recommend updating CodeSniffer and your ruleset and see if it solves anything, and otherwise report the error to wpcs together with the code to reproduce the error :)
