### ISSUE TITLE
Call to undefined function simplexml_load_string()

### ISSUE THREAD

**Issue by renanbr** [AtomLinter/linter-phpcs#209]
First of all, thanks for this package.

When trying using this package I get the error "Call to undefined function simplexml_load_string()"

Note 1: When I run `phpcs` in terminal, it works fine, I hope the package is using the same executable
Note 2: The same occurs with [linter-phpmd](https://github.com/AtomLinter/linter-phpmd) and bz2 extension
Note 3: I have a "similar" environment in a macOS, and it works fine, for both packages

~~~
Error: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in phar:///usr/local/bin/phpcs/CodeSniffer.php:714
Stack trace:
#0 phar:///usr/local/bin/phpcs/CodeSniffer.php(562): PHP_CodeSniffer->processRuleset('phar:///usr/loc...')
#1 phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php(944): PHP_CodeSniffer->initStandard(Array, Array, Array)
#2 phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#3 /usr/local/bin/phpcs(6): PHP_CodeSniffer_CLI->runphpcs()
#4 {main}
  thrown in phar:///usr/local/bin/phpcs/CodeSniffer.php on line 714
    at ChildProcess.<anonymous> (/home/renan/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
---
```
Error: PHP Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in phar:///usr/local/bin/phpcs/CodeSniffer.php:714 Stack trace:

#0 phar:///usr/local/bin/phpcs/CodeSniffer.php(562): PHP_CodeSniffer->processRuleset('phar:///usr/loc...')

#1 phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php(944): PHP_CodeSniffer->initStandard(Array, Array, Array)

#2 phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()

#3 /usr/local/bin/phpcs(6): PHP_CodeSniffer_CLI->runphpcs()

#4 {main} thrown in phar:///usr/local/bin/phpcs/CodeSniffer.php on line 714
```

## My environment

Ubuntu 16.04
Atom 1.11.1
linter-phpcs 1.5.1
Nothing in my `~/.atom/config.cson` related to linter-phpcs

`which php` = `/home/renan/.phpbrew/php/php-7.0.11/bin/php`

The file `vendor/bind/phpcs` does not exist into the project I'm working in, I've tried disable the "Search for executables" option, and `which phpcs` = `/usr/local/bin/phpcs`

`php --version` 
```
PHP 7.0.11 (cli) (built: Oct 12 2016 15:14:33) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```
---
`php -m`
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

**Comment by Arcanemagus** [comment]
All of that is coming from the `stderr` output from PHPCS, so it's an issue on your system.

On the system where this is happening does PHPCS work when you pipe content in via `stdin`?

**Comment by jyggen** [comment]
Have you specified which php executable `linter-phpcs` should use? It _could_ be using Ubuntu's default PHP executable instead of  `/home/renan/.phpbrew/php/php-7.0.11/bin/php`, and I don't think Ubuntu ships with `ext-simplexml` out of the box.

**Comment by renanbr** [comment]
Thanks for your response @Arcanemagus, it runs whell when I try `cat sample.php | phpcs` the problem was actually with my environment

Thanks for @jyggen the tip, the problem is exactly that, I messed up my environment. When I start Atom from a terminal where phpbrew is ok, it runs smoothly 👍 

closing it
