### ISSUE TITLE
Error: sh: rvm_debug: line 1: syntax error: unexpected end of file sh: error importing function definition for `rvm_debug'

### ISSUE THREAD

**Issue by vjandrea** [AtomLinter/linter-phpcs#238]
Hello there,
i keep getting this error:

`Error: sh: rvm_debug: line 1: syntax error: unexpected end of file
sh: error importing function definition for `rvm_debug'
    at ChildProcess.<anonymous> (/Users/<me>/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

`$ phpcs --version
PHP_CodeSniffer version 2.8.0 (stable) by Squiz (http://www.squiz.net)`

**Comment by Arcanemagus** [comment]
Looks like you have an error somewhere in your shell profile scripts, likely around wherever `rvm_debug` is defined.
