### ISSUE TITLE
Failed to get methods for (class): Unexpected end of JSON input

### ISSUE THREAD

**Issue by godilley** [AtomLinter/linter-phpcs#320]
Whenever the linter tries to lint, it spams the following:

```
php-proxy.coffee? [sm]:50 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.execute (/home/george/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:48:40)
    at Object.methods (/home/george/.atom/packages/atom-autocomplete-php/lib/services/php-proxy.coffee:201:20)
    at Object.getMemberContext (/home/george/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:688:27)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (/home/george/.atom/packages/atom-autocomplete-php/lib/annotation/method-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (/home/george/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (/home/george/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (/home/george/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (/home/george/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:241:10)
    at /home/george/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1380:31
    at <anonymous>
php-file-parser.coffee? [sm]:699 Failed to get methods for Path\To\Class : Unexpected end of JSON input
php-file-parser.coffee? [sm]:699 Failed to get methods for Path\To\Class : Unexpected end of JSON input
php-file-parser.coffee? [sm]:699 Failed to get methods for Path\To\Class : Unexpected end of JSON input
```

**Comment by Arcanemagus** [comment]
From the stack trace it looks like this is an issue with `atom-autocomplete-php`, it just happens to be triggering around the same time 😉.
