### ISSUE TITLE
Failed to activate the linter-phpcs package

### ISSUE THREAD

**Issue by davidbarratt** [AtomLinter/linter-phpcs#33]
I think the dependency is supposed to be `linter` not `atom-linter` unless I have something wrong.

---------------------------------------

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package, v1.0.1

### Stack Trace

Failed to activate the linter-phpcs package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.provideLinter (/Users/dbarratt/.atom/packages/linter-phpcs/lib/main.coffee:80:17)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:369:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter-phpcs": {
    "codeStandardOrConfigFile": "Drupal",
    "executablePath": "/Users/dbarratt/sites/golfchannel/vendor/bin/phpcs"
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
behat-atom, v0.1.2
language-apache, v1.3.0
line-ending-converter, v1.2.0
linter, v1.2.0
linter-php, v0.0.15
linter-phpcs, v1.0.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
According to the package.json of the Linter package, you are correct: https://github.com/AtomLinter/Linter/blob/master/package.json :wink:

**Comment by steelbrain** [comment]
It's an update issue, and `atom-linter` is actually an npm helper module. Can you please remove and reinstall and report if it works for you?

**Comment by steelbrain** [comment]
I am 99.999% sure that a restart or cache clear would fix this, but if it does not, feel free to ping me.
