### ISSUE TITLE
Uncaught Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by uonick** [AtomLinter/linter-phpcs#333]
[Enter steps to reproduce:]

1. Just open Atom
2. Navigate to any PHP file

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package 1.6.8

### Stack Trace

Uncaught Error: Cannot find module 'tmp'

```
At module.js:545

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:23:12)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:139:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/index.js:139:16)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/index.js:329:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/packages/linter-php/lib/main.js:16:15)
    at installLinterPhpDeps (/packages/linter-php/lib/main.js:32:7)
```

### Non-Core Packages

```
atom-beautify 0.33.2 
atom-runner 2.7.1 
blade-snippets 0.2.0 
busy-signal 1.4.3 
dimmed-one-dark-syntax 1.9.5 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.25 
highlight-selected 0.14.0 
intentions 1.1.5 
language-blade 0.41.2 
language-gitignore 0.3.0 
language-lua 0.9.11 
language-pug 0.0.22 
language-vue 0.23.1 
laravel 0.7.1 
laravel-snippets 2.1.0 
linter 2.2.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
open-in-browser 0.5.2 
project-manager 3.3.6 
pug 0.8.0 
tabs-to-spaces 1.0.5 
todo-show 2.3.2 
```

**Comment by Arcanemagus** [comment]
Can you please update to v1.6.10 and try again? This _should_ be fixed now.

**Comment by uonick** [comment]
Nope :(

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) package 1.6.10


### Stack Trace

Uncaught Error: Cannot find module 'tmp'

```
At module.js:545

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:23:12)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:139:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/index.js:139:16)
    at /packages/linter-phpcs/node_modules/atom-linter/lib/index.js:329:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at loadDeps (/packages/linter-php/lib/main.js:16:15)
    at installLinterPhpDeps (/packages/linter-php/lib/main.js:32:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.2 
atom-runner 2.7.1 
blade-snippets 0.2.0 
busy-signal 1.4.3 
dimmed-one-dark-syntax 1.9.5 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.25 
highlight-selected 0.14.0 
intentions 1.1.5 
language-blade 0.41.2 
language-gitignore 0.3.0 
language-lua 0.9.11 
language-pug 0.0.22 
language-vue 0.23.1 
laravel 0.7.1 
laravel-snippets 2.1.0 
linter 2.2.0 
linter-php 1.5.1 
linter-phpcs 1.6.10 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
open-in-browser 0.5.2 
project-manager 3.3.6 
pug 0.8.0 
tabs-to-spaces 1.0.5 
todo-show 2.3.2 
```

**Comment by UziTech** [comment]
Closing this as stale. If this is still an issue for anyone we can reopen it.
