### ISSUE TITLE
When I save my php file, this error always display.What something have to do ? Please, thanks

### ISSUE THREAD

**Issue by NixusCN** [AtomLinter/linter-phpcs#49]
**spawn phpcs ENOENT**
···
Error: spawn phpcs ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
  at EventEmitter.ipc.sendSync (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as getPosition] (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\atom.js:530:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\atom.js:563:25)
  at C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:104:21
  at handler (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at elemData.handle (C:\Users\Nixus\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)···

**Comment by steelbrain** [comment]
It means you haven't installed `phpcs` or it isn't in your `$PATH` or you haven't specified it's path in config.
