### ISSUE TITLE
Error: PHP Notice: Undefined offset

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-phpcs#99]
```fish
Error: PHP Notice: Undefined offset: 3 in /usr/local/Cellar/php-code-sniffer/2.5.1/CodeSniffer/Tokenizers/PHP.php on line 668
Error: PHP Notice:  Undefined offset: 3 in /usr/local/Cellar/php-code-sniffer/2.5.1/CodeSniffer/Tokenizers/PHP.php on line 668
    at parameters.exit (/Users/cory/.atom/packages/linter-phpcs/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Settings:
![image](https://cloud.githubusercontent.com/assets/224636/12791255/4a7a0d30-ca74-11e5-8046-93eb7ac26016.png)

![image](https://cloud.githubusercontent.com/assets/224636/12791312/944be60e-ca74-11e5-95d3-b361294195ce.png)

`phpcs --standard=WordPress-VIP -p footer.php` works via CLI.

**Comment by Arcanemagus** [comment]
You aren't specifying that standard in your settings though, do you have a `phpcs.xml` file that says to use it?

**Comment by corysimmons** [comment]
Sorry, even when I use `phpcs -p footer.php` it works on the CLI.

No `phpcs.xml` file so it shouldn't be conflicting.

**Comment by Arcanemagus** [comment]
The error you posted is coming from `phpcs` itself anyway, so it's likely the issue had nothing to do with this package in the first place. I'll mark this as closed, but if you see it again we can try to diagnose it further :wink:.

**Comment by corysimmons** [comment]
:+1:
